name: Sync to Codeberg

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  codeberg-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure SSH and Push to Codeberg
        env:
          SSH_KEY: ${{ secrets.CODEBERG_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts
          git remote add codeberg git@codeberg.org:cakgup/pages.git
          git push codeberg main --force
